{% set version = "0.91.0" %}

package:
  name: pydstool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyDSTool/PyDSTool-{{ version }}.tar.gz
  sha256: f21044d721461310f0605b7a83fba6cba78d1703456042809bde9d772c9b5c95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.6
    - scipy >=1.0

test:
  imports:
    - PyDSTool
    - PyDSTool.Generator
    - PyDSTool.PyCont
    - PyDSTool.Toolbox
    - PyDSTool.Toolbox.optimizers
    - PyDSTool.Toolbox.optimizers.criterion
    - PyDSTool.Toolbox.optimizers.helpers
    - PyDSTool.Toolbox.optimizers.line_search
    - PyDSTool.Toolbox.optimizers.optimizer
    - PyDSTool.Toolbox.optimizers.step
    - PyDSTool.core
    - PyDSTool.core.codegenerators
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.ni.gsu.edu/~rclewley/PyDSTool/FrontPage.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: |
    PyDSTool is a sophisticated & integrated simulation and analysis environment
    for dynamical systems models of physical systems (ODEs, DAEs, maps, and
    hybrid systems).
  doc_url: http://www.ni.gsu.edu/~rclewley/PyDSTool/ProjectOverview.html
  dev_url: https://github.com/robclewley/pydstool

extra:
  recipe-maintainers:
    - ChrisRackauckas
    - repagh
