travis:
  secure:
    BINSTAR_TOKEN: tGMQFbudKDHL1dyBCrUteZCuEEOo2ss/evzFhIIEVMzrBUo1neuy7zywGYmDh3k9E7GN3dwiHi7HH78YCKgRjFOLxM0HyUBzWGlPjHjF2Ar97HjZK8yGz8cs88/WkJDsYCdXDd3iXCrI0UKR8ZAkI8JAkUOKJDYt44Z7smCr3DVDR10TDBAy8cmFqlpsZ2/P69IKIiykWmmjmK+Eu9P28QGvKh8OsNVq3XO4kePK2O6d0A3g1APNB7im6kF3JhPoH5aBGUOCjhYzWZ7q7wHv6SnBPt5JDEoc9pDnSNKzatoIKk29LdKnbKLyF/rmVckeGT5rhWKoeozIwkyb+4tYuhNSYOXWNsRPwx0CGnqHgS9xKR+SK1XaZ7rVR0j95tUqbD2LtdCOYlUm8aPHVCJXoUdLvwzNEjLrbXpOBrfMOWp0s/Mv66hlym+7TcI8TSYdSagqSosLIjdbWB+p5DOdJL3vCYOycrVAqmBCsJvfmpfFewFEclkkPYWc9aiVvpg/eDVDEAVrXvATbeI9xmGG+CAGUXdJ63KMrYbPl18TaTiu4X379GewJdSHkxxOd45h66NwMiQAHJf4Cahgmavd0qE8YXjf1H9cCIM/nuOQy62F0ZTdpHPfPcYgza50FEWGa+kXqUmKbBzeNx75GK+URaC1y+4r2x+mIumZFoAQ2Jg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
